"use strict";

/* =========================================================
   PRODUCT DATA
   Every available product asset has one catalog entry.
   ========================================================= */

const products = [
  createProduct(
    "nex-m1",
    "NEX M1",
    "peripherals",
    "Peripherals",
    79,
    "Gaming_Mouse/Gaming_Mouse_NEX_M1_Photo1.png",
    "Ultra-light wireless mouse for accurate competitive play.",
    [
      ["DPI", "26K"],
      ["Battery", "70h"],
      ["Weight", "59g"],
    ],
  ),
  createProduct(
    "nex-m2",
    "NEX M2",
    "peripherals",
    "Peripherals",
    89,
    "Gaming_Mouse/Gaming_Mouse_NEX_M2_Photo1.png",
    "High-speed mouse with precise tracking and a lightweight shell.",
    [
      ["DPI", "32K"],
      ["Polling", "8K"],
      ["Weight", "58g"],
    ],
  ),
  createProduct(
    "nex-k1",
    "NEX K1",
    "peripherals",
    "Peripherals",
    129,
    "Gaming_Keyboard/Gaming_Keyboard_NEX_K1(1)(1).png",
    "Tournament-ready mechanical keyboard with responsive RGB switches.",
    [
      ["Switches", "Mechanical"],
      ["Response", "1ms"],
      ["Lighting", "RGB"],
    ],
  ),
  createProduct(
    "nex-k2",
    "NEX K2",
    "peripherals",
    "Peripherals",
    99,
    "Gaming_Keyboard/Gaming_Keyboard_NEX_K2.png",
    "Compact gaming keyboard built for fast actuation and durability.",
    [
      ["Layout", "TKL"],
      ["Switches", "Linear"],
      ["Lighting", "RGB"],
    ],
  ),
  createProduct(
    "nex-h1",
    "NEX H1",
    "peripherals",
    "Peripherals",
    109,
    "Gaming_Headset/Gaming_Headset_NEX_H1_Photo1.png",
    "Immersive wireless audio with a clear detachable microphone.",
    [
      ["Audio", "7.1"],
      ["Mic", "Detachable"],
      ["Battery", "40h"],
    ],
  ),
  createProduct(
    "nex-h2",
    "NEX H2",
    "peripherals",
    "Peripherals",
    119,
    "Gaming_Headset/Gaming_Headset_NEX_H2_Photo1.png",
    "Comfort-focused headset engineered for long competitive sessions.",
    [
      ["Audio", "Spatial"],
      ["Mic", "Clear voice"],
      ["Fit", "Memory foam"],
    ],
  ),
  createProduct(
    "nex-c1",
    "NEX C1",
    "peripherals",
    "Peripherals",
    69,
    "Gaming_Controller/Gaming_Controller_NEX_C1.png",
    "Responsive wireless controller with adaptive triggers.",
    [
      ["Connection", "Wireless"],
      ["Triggers", "Adaptive"],
      ["Battery", "30h"],
    ],
  ),
  createProduct(
    "nex-ch1",
    "NEX CH1",
    "setup",
    "Gaming Setup",
    249,
    "Gaming_Chair/Gaming_Chair_NEX_CH1_Photo1.png",
    "Ergonomic gaming chair designed for all-day support.",
    [
      ["Support", "Ergonomic"],
      ["Adjustments", "4D"],
      ["Frame", "Steel"],
    ],
  ),
  createProduct(
    "nex-d1",
    "NEX D1",
    "setup",
    "Gaming Setup",
    329,
    "Gaming_Desk/Gaming_Desk_NEX_D1.png",
    "Spacious gaming desk with a streamlined performance setup.",
    [
      ["Surface", "Wide"],
      ["Frame", "Steel"],
      ["Cable", "Managed"],
    ],
  ),
  createProduct(
    "nex-glow",
    "NEX GLOW",
    "cables-devices",
    "Cables & Devices",
    59,
    "Gaming_Desk_Light/Gaming_Desk_Light_NEX_GLOW.png",
    "Ambient RGB desk light for a focused gaming environment.",
    [
      ["Lighting", "RGB"],
      ["Control", "App"],
      ["Modes", "Dynamic"],
    ],
  ),
  createProduct(
    "nex-mic1",
    "NEX MIC1",
    "cables-devices",
    "Cables & Devices",
    99,
    "Gaming_Microphone/Gaming_Microphone_NEX_MIC1.png",
    "Clear desktop microphone for streaming and team communication.",
    [
      ["Pickup", "Cardioid"],
      ["Connection", "USB-C"],
      ["Control", "Touch mute"],
    ],
  ),
  createProduct(
    "nex-v1",
    "NEX V1",
    "monitor",
    "Monitor",
    299,
    "Gaming_Monitor/Gaming_Monitor_NEX_V1.png",
    "Fast gaming display with smooth motion and vivid color.",
    [
      ["Refresh", "165Hz"],
      ["Response", "1ms"],
      ["Panel", "IPS"],
    ],
  ),
  createProduct(
    "nex-v2",
    "NEX V2",
    "monitor",
    "Monitor",
    449,
    "Gaming_Monitor/Gaming_Monitor_NEX_V2.png",
    "Premium high-refresh display for competitive performance.",
    [
      ["Refresh", "240Hz"],
      ["Response", "1ms"],
      ["Resolution", "QHD"],
    ],
  ),
  createProduct(
    "nex-pad-xl",
    "NEX PAD XL",
    "peripherals",
    "Peripherals",
    39,
    "Gaming_Mousepad/Gaming_Mousepad_NEX_PAD_XL.png",
    "Extended low-friction surface for consistent aim and control.",
    [
      ["Size", "XL"],
      ["Surface", "Speed"],
      ["Base", "Non-slip"],
    ],
  ),
  createProduct(
    "nex-core-x",
    "NEX CORE X",
    "pc",
    "PC",
    1499,
    "Gaming_PC/Gaming_PC_NEX_CORE_X(1).png",
    "High-performance gaming PC built for demanding modern titles.",
    [
      ["CPU", "Performance"],
      ["GPU", "RTX class"],
      ["Cooling", "RGB"],
    ],
  ),
  createProduct(
    "nex-usb-hub",
    "NEX USB HUB",
    "cables-devices",
    "Cables & Devices",
    49,
    "PC_Accessories/PC_Accessories_NEX_USB_HUB_Photo1.png",
    "Multi-port USB hub for an organized desktop setup.",
    [
      ["Ports", "Multi-port"],
      ["Connection", "USB-C"],
      ["Power", "Pass-through"],
    ],
  ),
  createProduct(
    "nex-cam1",
    "NEX CAM1",
    "cables-devices",
    "Cables & Devices",
    79,
    "Webcam/Webcam_NEX_CAM1_Photo1.png",
    "Sharp webcam for streaming, calls, and content creation.",
    [
      ["Resolution", "1080p"],
      ["Frame rate", "60fps"],
      ["Focus", "Auto"],
    ],
  ),
];

function createProduct(
  id,
  name,
  category,
  categoryLabel,
  price,
  imageFile,
  description,
  specifications,
) {
  const image = `assets/products/${imageFile}`;

  return {
    id,
    name,
    category,
    categoryLabel,
    price,
    oldPrice: Math.round(price * 1.15),
    rating: 4.8,
    reviews: 100,
    image,
    cardImage: image,
    description,
    specifications,
  };
}
